# Generated by Django 5.0.7 on 2024-08-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('ssd', models.CharField(max_length=100)),
                ('hdd', models.CharField(max_length=100)),
                ('gc', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=100)),
                ('sn', models.CharField(max_length=100)),
            ],
        ),
    ]
